pipeline:
  backend:
    group: build
    image: elixir:1.6.0-alpine
    commands:
      - apk add --update git postgresql-client
      - mix local.hex --force
      - mix local.rebar --force
      - mix deps.get
      - mix deps.compile
      - mix test
  frontend:
    group: build
    image: node:latest
    commands:
      - cd app
      - yarn
      - yarn test

services:
  postgres:
    image: postgres:9.6-alpine
  influxdb:
    image: influxdb:1.3-alpine
