pipeline:
  backend:
    group: build
    image: elixir:1.5.2-alpine
    commands:
      - mix deps.get
      - mix deps.compile
      - mix test
  frontend:
    group: build
    image: node:latest
    commands:
      - yarn
      - yarn test

services:
  postgres:
    image: postgres:9.6-alpine
  influxdb:
    image: influxdb:1.3-alpine
